### PR TITLE
[TASK] Add request handler with reduced bootstrap

### PR DESCRIPTION
**Pull request by kitsunet**

### CODE REVIEW

**Comment by pumatertion** [comment]
Running into Fatal error on Flow 2.3: Call to a member function getContext() on a non-object in /Users/pumatertion/Sites/performance/typo3-flow-2.3/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php on line 322

We should support the latest release instead of master only.

**Comment by cedricziel** [comment]
Disclaimer: I didnt test this patch and I have a reason.

I dont think that this would lead to a compareable result at all. Flipping the coin and registering a new request handler could have been done in the relevant other frameworks as well but hasn't.
The thing is: All utilize standard routing to dispatch. What this PR accomplishes is bypassing the router completely and just dispatching.

This is by no means compareable.

1.) Routing is bypassed
2.) you create a micro bootstrap that could not resolve anything else. Do you expect people to write custom request handlers for every possible route in the chain? IMHO this feels a bit like `echo "<?php echo 'hello world'" > helloworld.php`

(Oh, fun fact: Laravel 5 is vanilla and even bootstraps it's whole security stack and still outperforms Flow. I dont even have a comparison term for the orders of magnitude of difference.)

**Comment by NamelessCoder** [comment]
Why not just override the `index.php` file with one that calls a pure PHP function and returns a string? That'd give a HUGE performance boost in benchmarks!

</sarcasm>

SCNR. I'm with Cedric here. Remember all those times when graphics card manufacturers tried to cheat the industry standard benchmarking by artificially short-circuiting otherwise expensive operations but only when a certain app was detected? This is that.

**Comment by kitsunet** [comment]
Yeah, this is rather a proof of "if I know I just need to write Hello World but have to use Flow, I would do this". It's perfectly valid userland code (not the nicest I agree), but I am also not a big fan of merging it. I still see the problem that the test itself is rather non descriptive. I don't doubt that Laravel is much faster, but the question is if the margin stays the same if you use all framework features in a test. Because who would use any framework to output Hello World. As you said Claus, if I know my requirement is to write Hello World...

<?php echo 'Hello World';

**Comment by NamelessCoder** [comment]
@kitsunet The test is actually pretty descriptive. It's a framework test which tests the out of the box experience; it clearly does not test and was not intended to test how fast you can make the framework by disabling as many features as possible.

The problem here is exactly the amount of features that come pre-loaded and impose heavy processing even when there is nothing significant to process. That's why your cheat improves the performance and that's how the problem can be solved!

**Comment by kitsunet** [comment]
Thanks, I am fully aware of that. The question remains: How much processing in the lines of "output a string" do you do in your average application? Anyway, I have profiled this stuff and also started to produce chnages for flow to intialize more stuff lazily.

**Comment by cedricziel** [comment]
Christian I appreciate a comparison, even comparing fruits of different kind. The result of the original benchmark by @pumatertion and @alexanderschnitzler was so impressive that there has to be truth underneath. Regardless of how much power Flow has under the hood - it has to deliver them at an acceptable and predictable niveau of speed and reliability. - Even without an expert with a screwdriver in the background.

To put that in some context, I asked myself how i would sell my clients a Flow based solution. "You have to put 15 times as much energy and money into ops to run this at comparable request scale and acceptable speed - and dont forget our budget we need to get a varnish in place."

I wonder which decision maker would think this is sane at any level.

The reason why I am so much after comparing Flow to its competitors is the simple fact that it's being advertised as `A Holistic Concept for Real World Applications [.] TYPO3 Flow is not a pick'n'mix store of motley components`. And that's only one sentence picked up.

Let me thank you nevertheless for all the energy you put into it! I do like many of the general ideas and concepts (and that's why I use them in an environment where they fit - a JVM). I dont think PHP is there yet to compete with those language features Flow polyfills.

**Comment by kitsunet** [comment]
Yes, that might well be true. I still will try to improve on that performance :)

**Pull request closed without merging**
